-- Scholary: +25 программ (сент 2026): Болашак, Chevening, Fulbright, Gates и др.
insert into programs (id,name,country,cc,levels,funding,base_adm,base_sch,req,deadline,note,fields,source_url,verified,verified_at) values
('x-prog-0','Болашак (международная стипендия РК)','Казахстан','kz',array['master','phd'],'полное покрытие + стипендия + перелёт',null,null,null,'обычно май–июль','обязательство отработки в РК 3–5 лет; топ-вузы из списка; по вузу',null,'https://bolashak.gov.kz/',false,null),
('x-nazarbayev-university','Гранты Nazarbayev University','Казахстан','kz',array['bachelor','master','phd'],'обучение 0 ₸ + стипендия + общежитие',null,null,null,'осень–зима','домашний вариант мирового уровня; NUFYP для недобравших; англ (IELTS 6.0–6.5)',null,'https://nu.edu.kz/admissions',false,null),
('x-gates-cambridge','Gates Cambridge','Великобритания','gb',array['master','phd'],'полное покрытие + стипендия',null,null,null,'окт–дек','сильнейший академический профиль; англ 7.0+',null,'https://www.gatescambridge.org/',false,null),
('x-clarendon-oxford','Clarendon (Oxford)','Великобритания','gb',array['master','phd'],'полное покрытие + стипендия',null,null,null,'дек–янв','автоматически при подаче в Oxford; англ 7.0+',null,'https://www.ox.ac.uk/clarendon',false,null),
('x-fulbright-foreign-student','Fulbright Foreign Student (Казахстан)','США','us',array['master'],'полное покрытие + стипендия + перелёт',null,null,null,'~май (за 1.5 года)','через посольство США в РК; TOEFL/IELTS',null,'https://kz.usembassy.gov/education-culture/',false,null),
('x-france-excellence-bgf','France Excellence (посольство, BGF)','Франция','fr',array['master'],'стипендия + соцпакет',null,null,null,'зима–весна','конкурс посольства Франции в РК; фр/англ',null,'https://www.kz.campusfrance.org/',false,null),
('x-daad-helmut-schmidt-public-policy','DAAD Helmut-Schmidt (Public Policy)','Германия','de',array['master'],'полное покрытие + €992/мес',null,null,null,'июнь–июль','госуправление/публичная политика; англ',null,'https://www.daad.de/en/',false,null),
('x-nl-scholarship-holland','NL Scholarship (быв. Holland)','Нидерланды','nl',array['bachelor','master'],'€5 000 (первый год)',null,null,null,'фев–май','частичная; комбинировать с грантами вузов; англ',null,'https://www.studyinnl.org/finances/nl-scholarship',false,null),
('x-orange-tulip-scholarship-kazakhstan','Orange Tulip Scholarship Kazakhstan','Нидерланды','nl',array['bachelor','master'],'скидки 30–100% на обучение',null,null,null,'окт–апр','специально для граждан РК; англ',null,'https://www.studyinnl.org/finances/orange-tulip-scholarship',false,null),
('x-lester-b-pearson-u-of-toronto','Lester B. Pearson (U of Toronto)','Канада','ca',array['bachelor'],'полное покрытие на 4 года',null,null,null,'ноя (номинация школы)','один из самых конкурентных в мире; англ',null,'https://future.utoronto.ca/pearson/',false,null),
('x-ubc-international-scholars','UBC International Scholars','Канада','ca',array['bachelor'],'need+merit, до полного',null,null,null,'дек','IMES/Karen McKellin; англ',null,'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/',false,null),
('x-prog-11','Стипендия правительства Румынии','Румыния','ro',array['bachelor','master','phd'],'обучение + общежитие + стипендия',null,null,null,'янв–март','низкий порог входа; рум (год языка) / англ',null,'https://www.mae.ro/en/node/10251',false,null),
('x-hamad-bin-khalifa-university','Hamad Bin Khalifa University','Катар','qa',array['master','phd'],'полное покрытие + стипендия',null,null,null,'~фев','Education City, Доха; англ',null,'https://www.hbku.edu.qa/en/admissions',false,null),
('x-khalifa-university','Khalifa University (полная стипендия)','ОАЭ','ae',array['bachelor','master','phd'],'обучение + стипендия + жильё',null,null,null,'фев–май','STEM, Абу-Даби; англ',null,'https://www.ku.ac.ae/admissions',false,null),
('x-yenching-academy-peking','Yenching Academy (Peking)','Китай','cn',array['master'],'полное покрытие',null,null,null,'~ноя','China studies, междисциплинарно; англ',null,'https://yenchingacademy.pku.edu.cn/',false,null),
('x-adb-japan-scholarship-adb-jsp','ADB–Japan Scholarship (ADB-JSP)','Международные',null,array['master'],'полное покрытие + стипендия',null,null,null,'за 6 мес до программы','РК — член АБР; вузы-партнёры в Азии; англ',null,'https://www.adb.org/work-with-us/careers/japan-scholarship-program',false,null),
('x-aga-khan-foundation-isp','Aga Khan Foundation ISP','Международные',null,array['master','phd'],'50% грант + 50% беспроцентный заём',null,null,null,'янв–март','есть офис в РК; англ',null,'https://the.akdn/en/how-we-work/our-agencies/aga-khan-foundation/international-scholarship-programme',false,null),
('x-kaist-international-scholarship','KAIST International Scholarship','Корея','kr',array['bachelor','master','phd'],'обучение + стипендия',null,null,null,'сен (early) / янв','STEM; отдельно от GKS; англ',null,'https://admission.kaist.ac.kr/intl-undergraduate/',false,null)
on conflict (id) do nothing;
